/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export interface CreatedApiKey {
  client_id: string;
  client_secret: string;
  created_at: string;
  expires_at?: string;
  name?: string;
}
