/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export type EventLevel = typeof EventLevel[keyof typeof EventLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventLevel = {
  error: 'error',
  warn: 'warn',
  info: 'info',
} as const;
