/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */
import type { EventLevel } from './eventLevel';

export interface EventHistory {
  created_at: string;
  details?: string;
  event_type: string;
  id: string;
  level: EventLevel;
}
