/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export type GetUsageParams = {
from: string;
to: string;
/**
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
cursor?: string;
};
