/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequest {
  email: string;
  /** @minLength 1 */
  password: string;
}
