/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export interface NewApiKey {
  expires_at?: string;
  /** @maxLength 255 */
  name?: string;
  user_id: number;
}
