/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */
import type { EventLevel } from './eventLevel';

export interface NewEvent {
  details?: string;
  /** @minLength 1 */
  event_type: string;
  level: EventLevel;
}
