/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export interface NewItem {
  description?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
}
