/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from './post';

export interface PostPage {
  data: Post[];
  nextCursor?: string;
}
