/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export interface Post {
  content: string;
  createdAt: string;
  id: number;
  updatedAt: string;
  userId: number;
}
