/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */

export type TokenRequestGrantType = typeof TokenRequestGrantType[keyof typeof TokenRequestGrantType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenRequestGrantType = {
  client_credentials: 'client_credentials',
} as const;
