/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lab API
 * OpenAPI spec version: 1.0.0
 */
import type { TokenRequestGrantType } from './tokenRequestGrantType';

export interface TokenRequest {
  client_id: string;
  /** @minLength 1 */
  client_secret: string;
  grant_type: TokenRequestGrantType;
}
