// Package shared provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package shared

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for EventLevel.
const (
	EventLevelError EventLevel = "error"
	EventLevelInfo  EventLevel = "info"
	EventLevelWarn  EventLevel = "warn"
)

// Valid indicates whether the value is a known member of the EventLevel enum.
func (e EventLevel) Valid() bool {
	switch e {
	case EventLevelError:
		return true
	case EventLevelInfo:
		return true
	case EventLevelWarn:
		return true
	default:
		return false
	}
}

// Defines values for TokenRequestGrantType.
const (
	ClientCredentials TokenRequestGrantType = "client_credentials"
)

// Valid indicates whether the value is a known member of the TokenRequestGrantType enum.
func (e TokenRequestGrantType) Valid() bool {
	switch e {
	case ClientCredentials:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	ClientId   openapi_types.UUID `json:"client_id"`
	CreatedAt  time.Time          `json:"created_at"`
	ExpiresAt  *time.Time         `json:"expires_at,omitempty"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       *string            `json:"name,omitempty"`
	RevokedAt  *time.Time         `json:"revoked_at,omitempty"`
}

// CreatedApiKey defines model for CreatedApiKey.
type CreatedApiKey struct {
	ClientId     openapi_types.UUID `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	CreatedAt    time.Time          `json:"created_at"`
	ExpiresAt    *time.Time         `json:"expires_at,omitempty"`
	Name         *string            `json:"name,omitempty"`
}

// DailyUsage defines model for DailyUsage.
type DailyUsage struct {
	Count int                `json:"count"`
	Date  openapi_types.Date `json:"date"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// EventHistory defines model for EventHistory.
type EventHistory struct {
	CreatedAt time.Time          `json:"created_at"`
	Details   *string            `json:"details,omitempty"`
	EventType string             `json:"event_type"`
	Id        openapi_types.UUID `json:"id"`
	Level     EventLevel         `json:"level"`
}

// EventLevel defines model for EventLevel.
type EventLevel string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Item defines model for Item.
type Item struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// NewApiKey defines model for NewApiKey.
type NewApiKey struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UserId    int64      `json:"user_id"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	Details   *string    `json:"details,omitempty"`
	EventType string     `json:"event_type"`
	Level     EventLevel `json:"level"`
}

// NewItem defines model for NewItem.
type NewItem struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// NewPost defines model for NewPost.
type NewPost struct {
	Content string `json:"content"`
}

// NewUsage defines model for NewUsage.
type NewUsage struct {
	Operation string    `json:"operation"`
	Timestamp time.Time `json:"timestamp"`
	UserId    int64     `json:"user_id"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email    openapi_types.Email `json:"email"`
	Username string              `json:"username"`
}

// Post defines model for Post.
type Post struct {
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	UpdatedAt time.Time `json:"updatedAt"`
	UserId    int64     `json:"userId"`
}

// PostPage defines model for PostPage.
type PostPage struct {
	Data       []Post  `json:"data"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     openapi_types.UUID    `json:"client_id"`
	ClientSecret string                `json:"client_secret"`
	GrantType    TokenRequestGrantType `json:"grant_type"`
}

// TokenRequestGrantType defines model for TokenRequest.GrantType.
type TokenRequestGrantType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

// UpdatePost defines model for UpdatePost.
type UpdatePost struct {
	Content string `json:"content"`
}

// UsageItem defines model for UsageItem.
type UsageItem struct {
	Id        int64     `json:"id"`
	Operation string    `json:"operation"`
	Timestamp time.Time `json:"timestamp"`
	UserId    int64     `json:"user_id"`
}

// UsagePage defines model for UsagePage.
type UsagePage struct {
	Data       []UsageItem `json:"data"`
	NextCursor *string     `json:"next_cursor,omitempty"`
}

// UsageStats defines model for UsageStats.
type UsageStats struct {
	Data []DailyUsage `json:"data"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	Username  string    `json:"username"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPostsParams defines parameters for ListPosts.
type ListPostsParams struct {
	UserId int64   `form:"userId" json:"userId"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	From   time.Time `form:"from" json:"from"`
	To     time.Time `form:"to" json:"to"`
	Limit  *int      `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string   `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetUsageStatsParams defines parameters for GetUsageStats.
type GetUsageStatsParams struct {
	From time.Time `form:"from" json:"from"`
	To   time.Time `form:"to" json:"to"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = NewApiKey

// CreateChEventJSONRequestBody defines body for CreateChEvent for application/json ContentType.
type CreateChEventJSONRequestBody = NewEvent

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = NewEvent

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = NewItem

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = NewPost

// UpdatePostJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody = UpdatePost

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = TokenRequest

// CreateUsageJSONRequestBody defines body for CreateUsage for application/json ContentType.
type CreateUsageJSONRequestBody = NewUsage

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = NewUser

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys for the authenticated user
	// (GET /api-keys)
	ListApiKeys(c *gin.Context)
	// Create a new API key for a user
	// (POST /api-keys)
	CreateApiKey(c *gin.Context)
	// Revoke an API key
	// (DELETE /api-keys/{clientId})
	RevokeApiKey(c *gin.Context, clientId openapi_types.UUID)
	// Create a ClickHouse event (test endpoint)
	// (POST /ch-events)
	CreateChEvent(c *gin.Context)
	// Create an event
	// (POST /events)
	CreateEvent(c *gin.Context)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// List all items
	// (GET /items)
	ListItems(c *gin.Context, params ListItemsParams)
	// Create an item
	// (POST /items)
	CreateItem(c *gin.Context)
	// Delete an item by ID
	// (DELETE /items/{id})
	DeleteItem(c *gin.Context, id openapi_types.UUID)
	// Get an item by ID
	// (GET /items/{id})
	GetItem(c *gin.Context, id openapi_types.UUID)
	// Login with email and password to get a JWT access token
	// (POST /login)
	Login(c *gin.Context)
	// List posts for a user (cursor-paginated)
	// (GET /posts)
	ListPosts(c *gin.Context, params ListPostsParams)
	// Create a post for the authenticated user
	// (POST /posts)
	CreatePost(c *gin.Context)
	// Get a post by ID
	// (GET /posts/{id})
	GetPost(c *gin.Context, id int64)
	// Update a post's content (owner only)
	// (PATCH /posts/{id})
	UpdatePost(c *gin.Context, id int64)
	// Exchange client credentials for a JWT access token
	// (POST /token)
	CreateToken(c *gin.Context)
	// Get paginated raw usage records for the authenticated user
	// (GET /usage)
	GetUsage(c *gin.Context, params GetUsageParams)
	// Ingest a single usage record
	// (POST /usage)
	CreateUsage(c *gin.Context)
	// Get daily usage aggregates for the authenticated user
	// (GET /usage/stats)
	GetUsageStats(c *gin.Context, params GetUsageStatsParams)
	// Create a new user
	// (POST /users)
	CreateUser(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApiKeys(c)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApiKey(c)
}

// RevokeApiKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeApiKey(c *gin.Context) {

	var err error

	// ------------- Path parameter "clientId" -------------
	var clientId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "clientId", c.Param("clientId"), &clientId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clientId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeApiKey(c, clientId)
}

// CreateChEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateChEvent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateChEvent(c)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateEvent(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListItems(c, params)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItem(c)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteItem(c, id)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItem(c, id)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// ListPosts operation middleware
func (siw *ServerInterfaceWrapper) ListPosts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPostsParams

	// ------------- Required query parameter "userId" -------------

	if paramValue := c.Query("userId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument userId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "userId", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPosts(c, params)
}

// CreatePost operation middleware
func (siw *ServerInterfaceWrapper) CreatePost(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePost(c)
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPost(c, id)
}

// UpdatePost operation middleware
func (siw *ServerInterfaceWrapper) UpdatePost(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdatePost(c, id)
}

// CreateToken operation middleware
func (siw *ServerInterfaceWrapper) CreateToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateToken(c)
}

// GetUsage operation middleware
func (siw *ServerInterfaceWrapper) GetUsage(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsage(c, params)
}

// CreateUsage operation middleware
func (siw *ServerInterfaceWrapper) CreateUsage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUsage(c)
}

// GetUsageStats operation middleware
func (siw *ServerInterfaceWrapper) GetUsageStats(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageStatsParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsageStats(c, params)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api-keys", wrapper.ListApiKeys)
	router.POST(options.BaseURL+"/api-keys", wrapper.CreateApiKey)
	router.DELETE(options.BaseURL+"/api-keys/:clientId", wrapper.RevokeApiKey)
	router.POST(options.BaseURL+"/ch-events", wrapper.CreateChEvent)
	router.POST(options.BaseURL+"/events", wrapper.CreateEvent)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/items", wrapper.ListItems)
	router.POST(options.BaseURL+"/items", wrapper.CreateItem)
	router.DELETE(options.BaseURL+"/items/:id", wrapper.DeleteItem)
	router.GET(options.BaseURL+"/items/:id", wrapper.GetItem)
	router.POST(options.BaseURL+"/login", wrapper.Login)
	router.GET(options.BaseURL+"/posts", wrapper.ListPosts)
	router.POST(options.BaseURL+"/posts", wrapper.CreatePost)
	router.GET(options.BaseURL+"/posts/:id", wrapper.GetPost)
	router.PATCH(options.BaseURL+"/posts/:id", wrapper.UpdatePost)
	router.POST(options.BaseURL+"/token", wrapper.CreateToken)
	router.GET(options.BaseURL+"/usage", wrapper.GetUsage)
	router.POST(options.BaseURL+"/usage", wrapper.CreateUsage)
	router.GET(options.BaseURL+"/usage/stats", wrapper.GetUsageStats)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
}

type ListApiKeysRequestObject struct {
}

type ListApiKeysResponseObject interface {
	VisitListApiKeysResponse(w http.ResponseWriter) error
}

type ListApiKeys200JSONResponse []ApiKey

func (response ListApiKeys200JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListApiKeys401JSONResponse Error

func (response ListApiKeys401JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateApiKeyRequestObject struct {
	Body *CreateApiKeyJSONRequestBody
}

type CreateApiKeyResponseObject interface {
	VisitCreateApiKeyResponse(w http.ResponseWriter) error
}

type CreateApiKey201JSONResponse CreatedApiKey

func (response CreateApiKey201JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateApiKey404JSONResponse Error

func (response CreateApiKey404JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevokeApiKeyRequestObject struct {
	ClientId openapi_types.UUID `json:"clientId"`
}

type RevokeApiKeyResponseObject interface {
	VisitRevokeApiKeyResponse(w http.ResponseWriter) error
}

type RevokeApiKey204Response struct {
}

func (response RevokeApiKey204Response) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeApiKey401JSONResponse Error

func (response RevokeApiKey401JSONResponse) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RevokeApiKey404JSONResponse Error

func (response RevokeApiKey404JSONResponse) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateChEventRequestObject struct {
	Body *CreateChEventJSONRequestBody
}

type CreateChEventResponseObject interface {
	VisitCreateChEventResponse(w http.ResponseWriter) error
}

type CreateChEvent201JSONResponse EventHistory

func (response CreateChEvent201JSONResponse) VisitCreateChEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201JSONResponse EventHistory

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListItemsRequestObject struct {
	Params ListItemsParams
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200JSONResponse []Item

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateItemRequestObject struct {
	Body *CreateItemJSONRequestBody
}

type CreateItemResponseObject interface {
	VisitCreateItemResponse(w http.ResponseWriter) error
}

type CreateItem201JSONResponse Item

func (response CreateItem201JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteItemRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteItemResponseObject interface {
	VisitDeleteItemResponse(w http.ResponseWriter) error
}

type DeleteItem204Response struct {
}

func (response DeleteItem204Response) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteItem404JSONResponse Error

func (response DeleteItem404JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetItemRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetItemResponseObject interface {
	VisitGetItemResponse(w http.ResponseWriter) error
}

type GetItem200JSONResponse Item

func (response GetItem200JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetItem404JSONResponse Error

func (response GetItem404JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse TokenResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse Error

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListPostsRequestObject struct {
	Params ListPostsParams
}

type ListPostsResponseObject interface {
	VisitListPostsResponse(w http.ResponseWriter) error
}

type ListPosts200JSONResponse PostPage

func (response ListPosts200JSONResponse) VisitListPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePostRequestObject struct {
	Body *CreatePostJSONRequestBody
}

type CreatePostResponseObject interface {
	VisitCreatePostResponse(w http.ResponseWriter) error
}

type CreatePost201JSONResponse Post

func (response CreatePost201JSONResponse) VisitCreatePostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreatePost401JSONResponse Error

func (response CreatePost401JSONResponse) VisitCreatePostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPostRequestObject struct {
	Id int64 `json:"id"`
}

type GetPostResponseObject interface {
	VisitGetPostResponse(w http.ResponseWriter) error
}

type GetPost200JSONResponse Post

func (response GetPost200JSONResponse) VisitGetPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPost404JSONResponse Error

func (response GetPost404JSONResponse) VisitGetPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePostRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdatePostJSONRequestBody
}

type UpdatePostResponseObject interface {
	VisitUpdatePostResponse(w http.ResponseWriter) error
}

type UpdatePost200JSONResponse Post

func (response UpdatePost200JSONResponse) VisitUpdatePostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePost401JSONResponse Error

func (response UpdatePost401JSONResponse) VisitUpdatePostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePost404JSONResponse Error

func (response UpdatePost404JSONResponse) VisitUpdatePostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateTokenRequestObject struct {
	Body *CreateTokenJSONRequestBody
}

type CreateTokenResponseObject interface {
	VisitCreateTokenResponse(w http.ResponseWriter) error
}

type CreateToken200JSONResponse TokenResponse

func (response CreateToken200JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateToken400JSONResponse Error

func (response CreateToken400JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateToken401JSONResponse Error

func (response CreateToken401JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUsageRequestObject struct {
	Params GetUsageParams
}

type GetUsageResponseObject interface {
	VisitGetUsageResponse(w http.ResponseWriter) error
}

type GetUsage200JSONResponse UsagePage

func (response GetUsage200JSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsage401JSONResponse Error

func (response GetUsage401JSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateUsageRequestObject struct {
	Body *CreateUsageJSONRequestBody
}

type CreateUsageResponseObject interface {
	VisitCreateUsageResponse(w http.ResponseWriter) error
}

type CreateUsage201JSONResponse UsageItem

func (response CreateUsage201JSONResponse) VisitCreateUsageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUsage400JSONResponse Error

func (response CreateUsage400JSONResponse) VisitCreateUsageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUsageStatsRequestObject struct {
	Params GetUsageStatsParams
}

type GetUsageStatsResponseObject interface {
	VisitGetUsageStatsResponse(w http.ResponseWriter) error
}

type GetUsageStats200JSONResponse UsageStats

func (response GetUsageStats200JSONResponse) VisitGetUsageStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsageStats401JSONResponse Error

func (response GetUsageStats401JSONResponse) VisitGetUsageStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser409JSONResponse Error

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List API keys for the authenticated user
	// (GET /api-keys)
	ListApiKeys(ctx context.Context, request ListApiKeysRequestObject) (ListApiKeysResponseObject, error)
	// Create a new API key for a user
	// (POST /api-keys)
	CreateApiKey(ctx context.Context, request CreateApiKeyRequestObject) (CreateApiKeyResponseObject, error)
	// Revoke an API key
	// (DELETE /api-keys/{clientId})
	RevokeApiKey(ctx context.Context, request RevokeApiKeyRequestObject) (RevokeApiKeyResponseObject, error)
	// Create a ClickHouse event (test endpoint)
	// (POST /ch-events)
	CreateChEvent(ctx context.Context, request CreateChEventRequestObject) (CreateChEventResponseObject, error)
	// Create an event
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List all items
	// (GET /items)
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)
	// Create an item
	// (POST /items)
	CreateItem(ctx context.Context, request CreateItemRequestObject) (CreateItemResponseObject, error)
	// Delete an item by ID
	// (DELETE /items/{id})
	DeleteItem(ctx context.Context, request DeleteItemRequestObject) (DeleteItemResponseObject, error)
	// Get an item by ID
	// (GET /items/{id})
	GetItem(ctx context.Context, request GetItemRequestObject) (GetItemResponseObject, error)
	// Login with email and password to get a JWT access token
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// List posts for a user (cursor-paginated)
	// (GET /posts)
	ListPosts(ctx context.Context, request ListPostsRequestObject) (ListPostsResponseObject, error)
	// Create a post for the authenticated user
	// (POST /posts)
	CreatePost(ctx context.Context, request CreatePostRequestObject) (CreatePostResponseObject, error)
	// Get a post by ID
	// (GET /posts/{id})
	GetPost(ctx context.Context, request GetPostRequestObject) (GetPostResponseObject, error)
	// Update a post's content (owner only)
	// (PATCH /posts/{id})
	UpdatePost(ctx context.Context, request UpdatePostRequestObject) (UpdatePostResponseObject, error)
	// Exchange client credentials for a JWT access token
	// (POST /token)
	CreateToken(ctx context.Context, request CreateTokenRequestObject) (CreateTokenResponseObject, error)
	// Get paginated raw usage records for the authenticated user
	// (GET /usage)
	GetUsage(ctx context.Context, request GetUsageRequestObject) (GetUsageResponseObject, error)
	// Ingest a single usage record
	// (POST /usage)
	CreateUsage(ctx context.Context, request CreateUsageRequestObject) (CreateUsageResponseObject, error)
	// Get daily usage aggregates for the authenticated user
	// (GET /usage/stats)
	GetUsageStats(ctx context.Context, request GetUsageStatsRequestObject) (GetUsageStatsResponseObject, error)
	// Create a new user
	// (POST /users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListApiKeys operation middleware
func (sh *strictHandler) ListApiKeys(ctx *gin.Context) {
	var request ListApiKeysRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListApiKeys(ctx, request.(ListApiKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApiKeys")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListApiKeysResponseObject); ok {
		if err := validResponse.VisitListApiKeysResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApiKey operation middleware
func (sh *strictHandler) CreateApiKey(ctx *gin.Context) {
	var request CreateApiKeyRequestObject

	var body CreateApiKeyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApiKey(ctx, request.(CreateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApiKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateApiKeyResponseObject); ok {
		if err := validResponse.VisitCreateApiKeyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeApiKey operation middleware
func (sh *strictHandler) RevokeApiKey(ctx *gin.Context, clientId openapi_types.UUID) {
	var request RevokeApiKeyRequestObject

	request.ClientId = clientId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeApiKey(ctx, request.(RevokeApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeApiKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RevokeApiKeyResponseObject); ok {
		if err := validResponse.VisitRevokeApiKeyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChEvent operation middleware
func (sh *strictHandler) CreateChEvent(ctx *gin.Context) {
	var request CreateChEventRequestObject

	var body CreateChEventJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChEvent(ctx, request.(CreateChEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateChEventResponseObject); ok {
		if err := validResponse.VisitCreateChEventResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(ctx *gin.Context) {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx, request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		if err := validResponse.VisitCreateEventResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(ctx *gin.Context, params ListItemsParams) {
	var request ListItemsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx, request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		if err := validResponse.VisitListItemsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateItem operation middleware
func (sh *strictHandler) CreateItem(ctx *gin.Context) {
	var request CreateItemRequestObject

	var body CreateItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateItem(ctx, request.(CreateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateItemResponseObject); ok {
		if err := validResponse.VisitCreateItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteItem operation middleware
func (sh *strictHandler) DeleteItem(ctx *gin.Context, id openapi_types.UUID) {
	var request DeleteItemRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteItem(ctx, request.(DeleteItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteItemResponseObject); ok {
		if err := validResponse.VisitDeleteItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetItem operation middleware
func (sh *strictHandler) GetItem(ctx *gin.Context, id openapi_types.UUID) {
	var request GetItemRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItem(ctx, request.(GetItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetItemResponseObject); ok {
		if err := validResponse.VisitGetItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPosts operation middleware
func (sh *strictHandler) ListPosts(ctx *gin.Context, params ListPostsParams) {
	var request ListPostsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPosts(ctx, request.(ListPostsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPosts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListPostsResponseObject); ok {
		if err := validResponse.VisitListPostsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePost operation middleware
func (sh *strictHandler) CreatePost(ctx *gin.Context) {
	var request CreatePostRequestObject

	var body CreatePostJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePost(ctx, request.(CreatePostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePost")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreatePostResponseObject); ok {
		if err := validResponse.VisitCreatePostResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPost operation middleware
func (sh *strictHandler) GetPost(ctx *gin.Context, id int64) {
	var request GetPostRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPost(ctx, request.(GetPostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPost")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPostResponseObject); ok {
		if err := validResponse.VisitGetPostResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePost operation middleware
func (sh *strictHandler) UpdatePost(ctx *gin.Context, id int64) {
	var request UpdatePostRequestObject

	request.Id = id

	var body UpdatePostJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePost(ctx, request.(UpdatePostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePost")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdatePostResponseObject); ok {
		if err := validResponse.VisitUpdatePostResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToken operation middleware
func (sh *strictHandler) CreateToken(ctx *gin.Context) {
	var request CreateTokenRequestObject

	var body CreateTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToken(ctx, request.(CreateTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateTokenResponseObject); ok {
		if err := validResponse.VisitCreateTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsage operation middleware
func (sh *strictHandler) GetUsage(ctx *gin.Context, params GetUsageParams) {
	var request GetUsageRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsage(ctx, request.(GetUsageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsageResponseObject); ok {
		if err := validResponse.VisitGetUsageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUsage operation middleware
func (sh *strictHandler) CreateUsage(ctx *gin.Context) {
	var request CreateUsageRequestObject

	var body CreateUsageJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUsage(ctx, request.(CreateUsageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUsage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateUsageResponseObject); ok {
		if err := validResponse.VisitCreateUsageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsageStats operation middleware
func (sh *strictHandler) GetUsageStats(ctx *gin.Context, params GetUsageStatsParams) {
	var request GetUsageStatsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsageStats(ctx, request.(GetUsageStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsageStats")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsageStatsResponseObject); ok {
		if err := validResponse.VisitGetUsageStatsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx *gin.Context) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb3W7jNhZ+FYK7wE4BJXam6QLruzQz23GbnQ3aDHoxCAJGOpbZSKSGpOJ4AwP7EPuE",
	"+yQFfyRLNvXjxFbSYq5iW+Th+f348Yh5xCFPM86AKYknj1iGc0iJ+XiW0Z9gqT9lgmcgFAXze5hQYOqG",
	"RvrLjIuUKDzBeU4jHGC1zABPsFSCshivAhwKIAqiGz2oMjwiCo4UTcE3Bx4yKkDuNCchUt3kcseVGElB",
	"j956IOCe3+0kzEz6klMBEZ58rnip5oPrch6//Q1Cpdc6t4/35G87WkIoQHlNGyoiDb5t81NN906/vSM0",
	"WX6SJAaP03jOquZTpiAGoadppbes6IynG2Tl+rR5LwQX24qkIAsN2xcoBnpl3wNTH6hUXPgS5AkBjUAR",
	"mkhvgoBe7cb+7HncMxETuIdEj/yrgBme4L+M1kgzcjAzMoZdmJGb/jBSrZCaSp1pUZE5ecTA8lSLAxOe",
	"AC+IYDjAlM14ZfZa7Q9AEjXfdrJUROWyO4xunE+xqYK0MXpnOwVPhoJminL2nAj1K1Az1wwNKrr67Lvg",
	"MWU/w5ccpNq2E1JCk5pe9hePYhmRcsGFsSKl7AJYrENy0lWjhcByvk/Lj7BoQtrnoFxKHgo93373nWdg",
	"LkFsgjhl6u+na6klSG3YVUxtMMck/LY1/Uu81cfPr2RPETdY4q+QrnRvCsEuqWNkNGh1yX35HHKmnN93",
	"WaiY1rBWw3amP5NGB+jclIqkWf+03UM2VtcNKho2WgZiF1ToVVD7CH0pJ3Br+wzozIEmmrULrveMR4Dz",
	"LNpVtrZy+qR4m1C76UFpctXAqkJNzrv05nVEFNF/qYJUdkGMicGqlE+EIEtT//CgznMhLf3qpHHEq+MV",
	"v4PmzeuZHLwDYGNBKmhcMBYnJRQQAVOUJNJDWDbMq0gKWqh1iwNkxpn0RIqEIUh5o/Qo/5biNk/Keiax",
	"EdVEMzfsqq1em1pb2GfXJ5Oag2G4AXD/Pta7vF8T2pfVvyvkG0fsoerXDm0o/ZuwrH2WJwm5TQBPlMgh",
	"eCoWmCV/UcS2RJ6he+WEuqV8f2V8++YTdpdyq33GvlPZcnucGrZ21vYTxCrAEsJcULX8RTvQWnoLRIA4",
	"y+2hzH77Z6Hqj79e4cA2rbQk+3St+lypDK+0YHPe01pTpdMDX5BbdHY5xQG+ByFNqeGT4/Hx2NUfIxnF",
	"E/zt8fj4W3OiUHOjzYhk9OgOluZLbNG9rAO9v+ILKpU9YEisfWIB1Yx/Ox5voA7JsoSGZvLoN2kL3iZP",
	"7xxzh5nt/No8KOJ//6RHnY5PdlKilfSbQ7VnqU+M5GrOBf0PRLXA4snnekg/X6+uAyzzNCVi6dynI4O0",
	"k9GMC6TmgLQ0vQmGOnmQzisdZBJLnWtG0LU+NzqQrwfEttecm2yWglTf82i5Nz+sz5SreiFoGFptZcH+",
	"AlBvHXoC4Qag///3f6jGARCVSM75giHOkiXiLASbHacDZIcEgRhXaMZz5vKjTACrMSKIwaJIBJMHpCHu",
	"q2BdlaNHa+Q0WtmTYwK22VdPiZ9Nd7dMiYwIkoICIU16agZjKr5ofExwIRVvBjeo+KKDF+o830iE063j",
	"Lf7I0blz/ssU60A58LEe/r7wYCOHCCtSw58P4fzIdBvsBt4CC+dz2z05GC5Y8QPDQq1f3IwKTZV3ntDw",
	"7gPPJSDjRfRGgVQIWJRxytQ3FZ+/t162Xu/n8q8O33Q4s25ucuu8bEl7CccPoFzT+pl0o81At0IDq6hZ",
	"ZYeicA7hXcUkJ8GaVDKbRgo1NSP82PwlB7Fcg3NCU6pwFYkjmJE8UXjydmwaSTTVR+qT8dh0htw3z9Hn",
	"egjC5j/LbDvWMCE+Q1Zo3cfmGUkS93DtZeu2LjJkVDhYBVoDhy3A9Zq7FR61nth0X5mjo0faTiXemd+d",
	"Q7uJBH0BCjH8bl462nqncDS6XaLpO2+2NiHbyzl2fPDcLM5jLxifH0B1BkfXQsJj29fzo4p583cgQKm9",
	"VeyFKvuLXL0n2hLC8eFD+C8qJWUx4gJRdk8SGqEZhSSSg50Tpm5Z08vRepTvWTc2Jx0xtKBq7oYSFpVj",
	"keIo1lmHfvz1Ctm+Lir7uttMXidcO1O4NCN6MYXyLUYPoGjujx6ahTQs4Nqc1RWGRLHyJY5vlzWqHWUk",
	"psy0G2zUPJzFPKgc59GbcGNu9XRhQ9vFZkxv/2Bsxr51GpbNrNdsYDOvvo1XniV14Pq18Ypgl1Vfcq8m",
	"cuACvz9y0Fjzhy6s10wPbAg32UGlNIkK59vxqbx3Gy5E+0eAihkDk4+uvPjTdwY1xWBcIb5gEOkEDEmS",
	"uFeUvYHIxs9l8d8kcrqjN1qqMM3vbxpAqHzX3bb5XDnqcojcq91J+Ep9XwH1rVzGCJC9eBAFWi93X9x0",
	"pOsY+v4hnBMWg3v9UhXheFA/IpwXN8OadkP7nrkXD54JnvaD29YL737hih9MdAvHtrS6QrL/mCx7fWui",
	"D80WZIFMXiABIRcDFsTTmaHmFC0W9OOKNte7DgZFRRzoZOAudgx7NKhch+k4HwwAzN+TCIlyf6pGecpi",
	"kJo8auBOoBZjTxxLgBvJ4tpNK8zZyzl/Dqw7OJxYZ3nCZ64nGVaFzP+1SBQLnmeWbEX2htUfAE0iY4bN",
	"MBLHAmKiYEcgsQlo8uixA1PM/INBCojhEQVEJ5j8Y5hbIbqsNJ1yfcNEAImWSBHNilquiTRcDFmtfg8A",
	"AP//UOBtIN84AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
