/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsageIndexRouteImport } from './routes/usage/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageIndexRoute = UsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/config/': typeof ConfigIndexRoute
  '/events/': typeof EventsIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/usage/': typeof UsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/config': typeof ConfigIndexRoute
  '/events': typeof EventsIndexRoute
  '/items': typeof ItemsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/usage': typeof UsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/config/': typeof ConfigIndexRoute
  '/events/': typeof EventsIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/usage/': typeof UsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/config/'
    | '/events/'
    | '/items/'
    | '/posts/'
    | '/usage/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/config' | '/events' | '/items' | '/posts' | '/usage'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/config/'
    | '/events/'
    | '/items/'
    | '/posts/'
    | '/usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  UsageIndexRoute: typeof UsageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage/': {
      id: '/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof UsageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  UsageIndexRoute: UsageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
