// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vitaliizinchenko/lab/internal/usage/models"
)

func newApiUsage(db *gorm.DB, opts ...gen.DOOption) apiUsage {
	_apiUsage := apiUsage{}

	_apiUsage.apiUsageDo.UseDB(db, opts...)
	_apiUsage.apiUsageDo.UseModel(&models.ApiUsage{})

	tableName := _apiUsage.apiUsageDo.TableName()
	_apiUsage.ALL = field.NewAsterisk(tableName)
	_apiUsage.ID = field.NewInt64(tableName, "id")
	_apiUsage.Timestamp = field.NewTime(tableName, "timestamp")
	_apiUsage.UserID = field.NewInt64(tableName, "user_id")
	_apiUsage.Operation = field.NewString(tableName, "operation")

	_apiUsage.fillFieldMap()

	return _apiUsage
}

type apiUsage struct {
	apiUsageDo

	ALL       field.Asterisk
	ID        field.Int64
	Timestamp field.Time
	UserID    field.Int64
	Operation field.String

	fieldMap map[string]field.Expr
}

func (a apiUsage) Table(newTableName string) *apiUsage {
	a.apiUsageDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a apiUsage) As(alias string) *apiUsage {
	a.apiUsageDo.DO = *(a.apiUsageDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *apiUsage) updateTableName(table string) *apiUsage {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Timestamp = field.NewTime(table, "timestamp")
	a.UserID = field.NewInt64(table, "user_id")
	a.Operation = field.NewString(table, "operation")

	a.fillFieldMap()

	return a
}

func (a *apiUsage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *apiUsage) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["id"] = a.ID
	a.fieldMap["timestamp"] = a.Timestamp
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["operation"] = a.Operation
}

func (a apiUsage) clone(db *gorm.DB) apiUsage {
	a.apiUsageDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a apiUsage) replaceDB(db *gorm.DB) apiUsage {
	a.apiUsageDo.ReplaceDB(db)
	return a
}

type apiUsageDo struct{ gen.DO }

type IApiUsageDo interface {
	gen.SubQuery
	Debug() IApiUsageDo
	WithContext(ctx context.Context) IApiUsageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IApiUsageDo
	WriteDB() IApiUsageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IApiUsageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IApiUsageDo
	Not(conds ...gen.Condition) IApiUsageDo
	Or(conds ...gen.Condition) IApiUsageDo
	Select(conds ...field.Expr) IApiUsageDo
	Where(conds ...gen.Condition) IApiUsageDo
	Order(conds ...field.Expr) IApiUsageDo
	Distinct(cols ...field.Expr) IApiUsageDo
	Omit(cols ...field.Expr) IApiUsageDo
	Join(table schema.Tabler, on ...field.Expr) IApiUsageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IApiUsageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IApiUsageDo
	Group(cols ...field.Expr) IApiUsageDo
	Having(conds ...gen.Condition) IApiUsageDo
	Limit(limit int) IApiUsageDo
	Offset(offset int) IApiUsageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IApiUsageDo
	Unscoped() IApiUsageDo
	Create(values ...*models.ApiUsage) error
	CreateInBatches(values []*models.ApiUsage, batchSize int) error
	Save(values ...*models.ApiUsage) error
	First() (*models.ApiUsage, error)
	Take() (*models.ApiUsage, error)
	Last() (*models.ApiUsage, error)
	Find() ([]*models.ApiUsage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ApiUsage, err error)
	FindInBatches(result *[]*models.ApiUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ApiUsage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IApiUsageDo
	Assign(attrs ...field.AssignExpr) IApiUsageDo
	Joins(fields ...field.RelationField) IApiUsageDo
	Preload(fields ...field.RelationField) IApiUsageDo
	FirstOrInit() (*models.ApiUsage, error)
	FirstOrCreate() (*models.ApiUsage, error)
	FindByPage(offset int, limit int) (result []*models.ApiUsage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IApiUsageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a apiUsageDo) Debug() IApiUsageDo {
	return a.withDO(a.DO.Debug())
}

func (a apiUsageDo) WithContext(ctx context.Context) IApiUsageDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a apiUsageDo) ReadDB() IApiUsageDo {
	return a.Clauses(dbresolver.Read)
}

func (a apiUsageDo) WriteDB() IApiUsageDo {
	return a.Clauses(dbresolver.Write)
}

func (a apiUsageDo) Session(config *gorm.Session) IApiUsageDo {
	return a.withDO(a.DO.Session(config))
}

func (a apiUsageDo) Clauses(conds ...clause.Expression) IApiUsageDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a apiUsageDo) Returning(value interface{}, columns ...string) IApiUsageDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a apiUsageDo) Not(conds ...gen.Condition) IApiUsageDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a apiUsageDo) Or(conds ...gen.Condition) IApiUsageDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a apiUsageDo) Select(conds ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a apiUsageDo) Where(conds ...gen.Condition) IApiUsageDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a apiUsageDo) Order(conds ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a apiUsageDo) Distinct(cols ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a apiUsageDo) Omit(cols ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a apiUsageDo) Join(table schema.Tabler, on ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a apiUsageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a apiUsageDo) RightJoin(table schema.Tabler, on ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a apiUsageDo) Group(cols ...field.Expr) IApiUsageDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a apiUsageDo) Having(conds ...gen.Condition) IApiUsageDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a apiUsageDo) Limit(limit int) IApiUsageDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a apiUsageDo) Offset(offset int) IApiUsageDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a apiUsageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IApiUsageDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a apiUsageDo) Unscoped() IApiUsageDo {
	return a.withDO(a.DO.Unscoped())
}

func (a apiUsageDo) Create(values ...*models.ApiUsage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a apiUsageDo) CreateInBatches(values []*models.ApiUsage, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a apiUsageDo) Save(values ...*models.ApiUsage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a apiUsageDo) First() (*models.ApiUsage, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiUsage), nil
	}
}

func (a apiUsageDo) Take() (*models.ApiUsage, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiUsage), nil
	}
}

func (a apiUsageDo) Last() (*models.ApiUsage, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiUsage), nil
	}
}

func (a apiUsageDo) Find() ([]*models.ApiUsage, error) {
	result, err := a.DO.Find()
	return result.([]*models.ApiUsage), err
}

func (a apiUsageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ApiUsage, err error) {
	buf := make([]*models.ApiUsage, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a apiUsageDo) FindInBatches(result *[]*models.ApiUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a apiUsageDo) Attrs(attrs ...field.AssignExpr) IApiUsageDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a apiUsageDo) Assign(attrs ...field.AssignExpr) IApiUsageDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a apiUsageDo) Joins(fields ...field.RelationField) IApiUsageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a apiUsageDo) Preload(fields ...field.RelationField) IApiUsageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a apiUsageDo) FirstOrInit() (*models.ApiUsage, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiUsage), nil
	}
}

func (a apiUsageDo) FirstOrCreate() (*models.ApiUsage, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiUsage), nil
	}
}

func (a apiUsageDo) FindByPage(offset int, limit int) (result []*models.ApiUsage, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a apiUsageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a apiUsageDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a apiUsageDo) Delete(models ...*models.ApiUsage) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *apiUsageDo) withDO(do gen.Dao) *apiUsageDo {
	a.DO = *do.(*gen.DO)
	return a
}
