// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vitaliizinchenko/lab/internal/usage/models"
)

func newUsage(db *gorm.DB, opts ...gen.DOOption) usage {
	_usage := usage{}

	_usage.usageDo.UseDB(db, opts...)
	_usage.usageDo.UseModel(&models.Usage{})

	tableName := _usage.usageDo.TableName()
	_usage.ALL = field.NewAsterisk(tableName)
	_usage.ID = field.NewInt64(tableName, "id")
	_usage.Timestamp = field.NewTime(tableName, "timestamp")
	_usage.UserID = field.NewInt64(tableName, "user_id")
	_usage.Operation = field.NewString(tableName, "operation")

	_usage.fillFieldMap()

	return _usage
}

type usage struct {
	usageDo

	ALL       field.Asterisk
	ID        field.Int64
	Timestamp field.Time
	UserID    field.Int64
	Operation field.String

	fieldMap map[string]field.Expr
}

func (u usage) Table(newTableName string) *usage {
	u.usageDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u usage) As(alias string) *usage {
	u.usageDo.DO = *(u.usageDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *usage) updateTableName(table string) *usage {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.Timestamp = field.NewTime(table, "timestamp")
	u.UserID = field.NewInt64(table, "user_id")
	u.Operation = field.NewString(table, "operation")

	u.fillFieldMap()

	return u
}

func (u *usage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *usage) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["id"] = u.ID
	u.fieldMap["timestamp"] = u.Timestamp
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["operation"] = u.Operation
}

func (u usage) clone(db *gorm.DB) usage {
	u.usageDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u usage) replaceDB(db *gorm.DB) usage {
	u.usageDo.ReplaceDB(db)
	return u
}

type usageDo struct{ gen.DO }

type IUsageDo interface {
	gen.SubQuery
	Debug() IUsageDo
	WithContext(ctx context.Context) IUsageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUsageDo
	WriteDB() IUsageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUsageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUsageDo
	Not(conds ...gen.Condition) IUsageDo
	Or(conds ...gen.Condition) IUsageDo
	Select(conds ...field.Expr) IUsageDo
	Where(conds ...gen.Condition) IUsageDo
	Order(conds ...field.Expr) IUsageDo
	Distinct(cols ...field.Expr) IUsageDo
	Omit(cols ...field.Expr) IUsageDo
	Join(table schema.Tabler, on ...field.Expr) IUsageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUsageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUsageDo
	Group(cols ...field.Expr) IUsageDo
	Having(conds ...gen.Condition) IUsageDo
	Limit(limit int) IUsageDo
	Offset(offset int) IUsageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUsageDo
	Unscoped() IUsageDo
	Create(values ...*models.Usage) error
	CreateInBatches(values []*models.Usage, batchSize int) error
	Save(values ...*models.Usage) error
	First() (*models.Usage, error)
	Take() (*models.Usage, error)
	Last() (*models.Usage, error)
	Find() ([]*models.Usage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Usage, err error)
	FindInBatches(result *[]*models.Usage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Usage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUsageDo
	Assign(attrs ...field.AssignExpr) IUsageDo
	Joins(fields ...field.RelationField) IUsageDo
	Preload(fields ...field.RelationField) IUsageDo
	FirstOrInit() (*models.Usage, error)
	FirstOrCreate() (*models.Usage, error)
	FindByPage(offset int, limit int) (result []*models.Usage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUsageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u usageDo) Debug() IUsageDo {
	return u.withDO(u.DO.Debug())
}

func (u usageDo) WithContext(ctx context.Context) IUsageDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u usageDo) ReadDB() IUsageDo {
	return u.Clauses(dbresolver.Read)
}

func (u usageDo) WriteDB() IUsageDo {
	return u.Clauses(dbresolver.Write)
}

func (u usageDo) Session(config *gorm.Session) IUsageDo {
	return u.withDO(u.DO.Session(config))
}

func (u usageDo) Clauses(conds ...clause.Expression) IUsageDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u usageDo) Returning(value interface{}, columns ...string) IUsageDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u usageDo) Not(conds ...gen.Condition) IUsageDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u usageDo) Or(conds ...gen.Condition) IUsageDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u usageDo) Select(conds ...field.Expr) IUsageDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u usageDo) Where(conds ...gen.Condition) IUsageDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u usageDo) Order(conds ...field.Expr) IUsageDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u usageDo) Distinct(cols ...field.Expr) IUsageDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u usageDo) Omit(cols ...field.Expr) IUsageDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u usageDo) Join(table schema.Tabler, on ...field.Expr) IUsageDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u usageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUsageDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u usageDo) RightJoin(table schema.Tabler, on ...field.Expr) IUsageDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u usageDo) Group(cols ...field.Expr) IUsageDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u usageDo) Having(conds ...gen.Condition) IUsageDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u usageDo) Limit(limit int) IUsageDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u usageDo) Offset(offset int) IUsageDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u usageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUsageDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u usageDo) Unscoped() IUsageDo {
	return u.withDO(u.DO.Unscoped())
}

func (u usageDo) Create(values ...*models.Usage) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u usageDo) CreateInBatches(values []*models.Usage, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u usageDo) Save(values ...*models.Usage) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u usageDo) First() (*models.Usage, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Usage), nil
	}
}

func (u usageDo) Take() (*models.Usage, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Usage), nil
	}
}

func (u usageDo) Last() (*models.Usage, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Usage), nil
	}
}

func (u usageDo) Find() ([]*models.Usage, error) {
	result, err := u.DO.Find()
	return result.([]*models.Usage), err
}

func (u usageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Usage, err error) {
	buf := make([]*models.Usage, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u usageDo) FindInBatches(result *[]*models.Usage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u usageDo) Attrs(attrs ...field.AssignExpr) IUsageDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u usageDo) Assign(attrs ...field.AssignExpr) IUsageDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u usageDo) Joins(fields ...field.RelationField) IUsageDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u usageDo) Preload(fields ...field.RelationField) IUsageDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u usageDo) FirstOrInit() (*models.Usage, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Usage), nil
	}
}

func (u usageDo) FirstOrCreate() (*models.Usage, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Usage), nil
	}
}

func (u usageDo) FindByPage(offset int, limit int) (result []*models.Usage, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u usageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u usageDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u usageDo) Delete(models ...*models.Usage) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *usageDo) withDO(do gen.Dao) *usageDo {
	u.DO = *do.(*gen.DO)
	return u
}
