// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for EventLevel.
const (
	EventLevelError EventLevel = "error"
	EventLevelInfo  EventLevel = "info"
	EventLevelWarn  EventLevel = "warn"
)

// Defines values for TokenRequestGrantType.
const (
	ClientCredentials TokenRequestGrantType = "client_credentials"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	ClientId   openapi_types.UUID `json:"client_id"`
	CreatedAt  time.Time          `json:"created_at"`
	ExpiresAt  *time.Time         `json:"expires_at,omitempty"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       *string            `json:"name,omitempty"`
	RevokedAt  *time.Time         `json:"revoked_at,omitempty"`
}

// CreatedApiKey defines model for CreatedApiKey.
type CreatedApiKey struct {
	ClientId     openapi_types.UUID `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
	CreatedAt    time.Time          `json:"created_at"`
	ExpiresAt    *time.Time         `json:"expires_at,omitempty"`
	Name         *string            `json:"name,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// EventHistory defines model for EventHistory.
type EventHistory struct {
	CreatedAt time.Time          `json:"created_at"`
	Details   *string            `json:"details,omitempty"`
	EventType string             `json:"event_type"`
	Id        openapi_types.UUID `json:"id"`
	Level     EventLevel         `json:"level"`
}

// EventLevel defines model for EventLevel.
type EventLevel string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Item defines model for Item.
type Item struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// NewApiKey defines model for NewApiKey.
type NewApiKey struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UserId    int64      `json:"user_id"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	Details   *string    `json:"details,omitempty"`
	EventType string     `json:"event_type"`
	Level     EventLevel `json:"level"`
}

// NewItem defines model for NewItem.
type NewItem struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email    openapi_types.Email `json:"email"`
	Username string              `json:"username"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     openapi_types.UUID    `json:"client_id"`
	ClientSecret string                `json:"client_secret"`
	GrantType    TokenRequestGrantType `json:"grant_type"`
}

// TokenRequestGrantType defines model for TokenRequest.GrantType.
type TokenRequestGrantType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	Username  string    `json:"username"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = NewApiKey

// CreateChEventJSONRequestBody defines body for CreateChEvent for application/json ContentType.
type CreateChEventJSONRequestBody = NewEvent

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = NewEvent

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = NewItem

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = TokenRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = NewUser

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys for the authenticated user
	// (GET /api-keys)
	ListApiKeys(c *gin.Context)
	// Create a new API key for a user
	// (POST /api-keys)
	CreateApiKey(c *gin.Context)
	// Revoke an API key
	// (DELETE /api-keys/{clientId})
	RevokeApiKey(c *gin.Context, clientId openapi_types.UUID)
	// Create a ClickHouse event (test endpoint)
	// (POST /ch-events)
	CreateChEvent(c *gin.Context)
	// Create an event
	// (POST /events)
	CreateEvent(c *gin.Context)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// List all items
	// (GET /items)
	ListItems(c *gin.Context, params ListItemsParams)
	// Create an item
	// (POST /items)
	CreateItem(c *gin.Context)
	// Delete an item by ID
	// (DELETE /items/{id})
	DeleteItem(c *gin.Context, id openapi_types.UUID)
	// Get an item by ID
	// (GET /items/{id})
	GetItem(c *gin.Context, id openapi_types.UUID)
	// Exchange client credentials for a JWT access token
	// (POST /token)
	CreateToken(c *gin.Context)
	// Create a new user
	// (POST /users)
	CreateUser(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApiKeys(c)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApiKey(c)
}

// RevokeApiKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeApiKey(c *gin.Context) {

	var err error

	// ------------- Path parameter "clientId" -------------
	var clientId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "clientId", c.Param("clientId"), &clientId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter clientId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeApiKey(c, clientId)
}

// CreateChEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateChEvent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateChEvent(c)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateEvent(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListItems(c, params)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItem(c)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteItem(c, id)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItem(c, id)
}

// CreateToken operation middleware
func (siw *ServerInterfaceWrapper) CreateToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateToken(c)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api-keys", wrapper.ListApiKeys)
	router.POST(options.BaseURL+"/api-keys", wrapper.CreateApiKey)
	router.DELETE(options.BaseURL+"/api-keys/:clientId", wrapper.RevokeApiKey)
	router.POST(options.BaseURL+"/ch-events", wrapper.CreateChEvent)
	router.POST(options.BaseURL+"/events", wrapper.CreateEvent)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/items", wrapper.ListItems)
	router.POST(options.BaseURL+"/items", wrapper.CreateItem)
	router.DELETE(options.BaseURL+"/items/:id", wrapper.DeleteItem)
	router.GET(options.BaseURL+"/items/:id", wrapper.GetItem)
	router.POST(options.BaseURL+"/token", wrapper.CreateToken)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
}

type ListApiKeysRequestObject struct {
}

type ListApiKeysResponseObject interface {
	VisitListApiKeysResponse(w http.ResponseWriter) error
}

type ListApiKeys200JSONResponse []ApiKey

func (response ListApiKeys200JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListApiKeys401JSONResponse Error

func (response ListApiKeys401JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateApiKeyRequestObject struct {
	Body *CreateApiKeyJSONRequestBody
}

type CreateApiKeyResponseObject interface {
	VisitCreateApiKeyResponse(w http.ResponseWriter) error
}

type CreateApiKey201JSONResponse CreatedApiKey

func (response CreateApiKey201JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateApiKey404JSONResponse Error

func (response CreateApiKey404JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevokeApiKeyRequestObject struct {
	ClientId openapi_types.UUID `json:"clientId"`
}

type RevokeApiKeyResponseObject interface {
	VisitRevokeApiKeyResponse(w http.ResponseWriter) error
}

type RevokeApiKey204Response struct {
}

func (response RevokeApiKey204Response) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeApiKey401JSONResponse Error

func (response RevokeApiKey401JSONResponse) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RevokeApiKey404JSONResponse Error

func (response RevokeApiKey404JSONResponse) VisitRevokeApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateChEventRequestObject struct {
	Body *CreateChEventJSONRequestBody
}

type CreateChEventResponseObject interface {
	VisitCreateChEventResponse(w http.ResponseWriter) error
}

type CreateChEvent201JSONResponse EventHistory

func (response CreateChEvent201JSONResponse) VisitCreateChEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201JSONResponse EventHistory

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListItemsRequestObject struct {
	Params ListItemsParams
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200JSONResponse []Item

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateItemRequestObject struct {
	Body *CreateItemJSONRequestBody
}

type CreateItemResponseObject interface {
	VisitCreateItemResponse(w http.ResponseWriter) error
}

type CreateItem201JSONResponse Item

func (response CreateItem201JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteItemRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteItemResponseObject interface {
	VisitDeleteItemResponse(w http.ResponseWriter) error
}

type DeleteItem204Response struct {
}

func (response DeleteItem204Response) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteItem404JSONResponse Error

func (response DeleteItem404JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetItemRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetItemResponseObject interface {
	VisitGetItemResponse(w http.ResponseWriter) error
}

type GetItem200JSONResponse Item

func (response GetItem200JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetItem404JSONResponse Error

func (response GetItem404JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateTokenRequestObject struct {
	Body *CreateTokenJSONRequestBody
}

type CreateTokenResponseObject interface {
	VisitCreateTokenResponse(w http.ResponseWriter) error
}

type CreateToken200JSONResponse TokenResponse

func (response CreateToken200JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateToken400JSONResponse Error

func (response CreateToken400JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateToken401JSONResponse Error

func (response CreateToken401JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser409JSONResponse Error

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List API keys for the authenticated user
	// (GET /api-keys)
	ListApiKeys(ctx context.Context, request ListApiKeysRequestObject) (ListApiKeysResponseObject, error)
	// Create a new API key for a user
	// (POST /api-keys)
	CreateApiKey(ctx context.Context, request CreateApiKeyRequestObject) (CreateApiKeyResponseObject, error)
	// Revoke an API key
	// (DELETE /api-keys/{clientId})
	RevokeApiKey(ctx context.Context, request RevokeApiKeyRequestObject) (RevokeApiKeyResponseObject, error)
	// Create a ClickHouse event (test endpoint)
	// (POST /ch-events)
	CreateChEvent(ctx context.Context, request CreateChEventRequestObject) (CreateChEventResponseObject, error)
	// Create an event
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List all items
	// (GET /items)
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)
	// Create an item
	// (POST /items)
	CreateItem(ctx context.Context, request CreateItemRequestObject) (CreateItemResponseObject, error)
	// Delete an item by ID
	// (DELETE /items/{id})
	DeleteItem(ctx context.Context, request DeleteItemRequestObject) (DeleteItemResponseObject, error)
	// Get an item by ID
	// (GET /items/{id})
	GetItem(ctx context.Context, request GetItemRequestObject) (GetItemResponseObject, error)
	// Exchange client credentials for a JWT access token
	// (POST /token)
	CreateToken(ctx context.Context, request CreateTokenRequestObject) (CreateTokenResponseObject, error)
	// Create a new user
	// (POST /users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListApiKeys operation middleware
func (sh *strictHandler) ListApiKeys(ctx *gin.Context) {
	var request ListApiKeysRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListApiKeys(ctx, request.(ListApiKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApiKeys")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListApiKeysResponseObject); ok {
		if err := validResponse.VisitListApiKeysResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApiKey operation middleware
func (sh *strictHandler) CreateApiKey(ctx *gin.Context) {
	var request CreateApiKeyRequestObject

	var body CreateApiKeyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApiKey(ctx, request.(CreateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApiKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateApiKeyResponseObject); ok {
		if err := validResponse.VisitCreateApiKeyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeApiKey operation middleware
func (sh *strictHandler) RevokeApiKey(ctx *gin.Context, clientId openapi_types.UUID) {
	var request RevokeApiKeyRequestObject

	request.ClientId = clientId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeApiKey(ctx, request.(RevokeApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeApiKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RevokeApiKeyResponseObject); ok {
		if err := validResponse.VisitRevokeApiKeyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChEvent operation middleware
func (sh *strictHandler) CreateChEvent(ctx *gin.Context) {
	var request CreateChEventRequestObject

	var body CreateChEventJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChEvent(ctx, request.(CreateChEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateChEventResponseObject); ok {
		if err := validResponse.VisitCreateChEventResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(ctx *gin.Context) {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx, request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		if err := validResponse.VisitCreateEventResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(ctx *gin.Context, params ListItemsParams) {
	var request ListItemsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx, request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		if err := validResponse.VisitListItemsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateItem operation middleware
func (sh *strictHandler) CreateItem(ctx *gin.Context) {
	var request CreateItemRequestObject

	var body CreateItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateItem(ctx, request.(CreateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateItemResponseObject); ok {
		if err := validResponse.VisitCreateItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteItem operation middleware
func (sh *strictHandler) DeleteItem(ctx *gin.Context, id openapi_types.UUID) {
	var request DeleteItemRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteItem(ctx, request.(DeleteItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteItemResponseObject); ok {
		if err := validResponse.VisitDeleteItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetItem operation middleware
func (sh *strictHandler) GetItem(ctx *gin.Context, id openapi_types.UUID) {
	var request GetItemRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItem(ctx, request.(GetItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetItemResponseObject); ok {
		if err := validResponse.VisitGetItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToken operation middleware
func (sh *strictHandler) CreateToken(ctx *gin.Context) {
	var request CreateTokenRequestObject

	var body CreateTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToken(ctx, request.(CreateTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateTokenResponseObject); ok {
		if err := validResponse.VisitCreateTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx *gin.Context) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ3W7bNhR+FYLbxQaosdKmA+a7LO1at102dAl6EQQBIx1bbCRSIY+SeIGBPcSecE8y",
	"8Ee2ZVOy3djOze4siTw85/vOL/1IE1mUUoBATfuPVCcZFMz+PC75RxibX6WSJSjkYN8nOQeBVzw1D0Op",
	"Coa0T6uKpzSiOC6B9qlGxcWITiKaKGAI6ZVZNLc8ZQgvkBcQ2gMPJVegN9qTM41Xld7wJMEKMKuXPii4",
	"kzcbCbObbiuuIKX9izmUGhhcTvfJ66+QoDnrxH3eEt5utYZEAQZN2xcjLdh24dTQfSVub5WSahmvArRm",
	"ozWOrhcGZd+BwPdco1QhSr4BwhSQ8VwHKQFz2pV7Hfi8JvU53EFuVn6vYEj79LveLLZ7PrB71rBPduUi",
	"HlaqE9JQaTURM5n9RwqiKow4sPRE9J4pQSPKxVDO7Z6p/R5YjtkyyBoZVno1jX5dSLEBQtHK3vFG5OlE",
	"8RK5FE9haL2QsHvt0mhO15B9p3DfljWeErEFe/gEYmRIefn6dWBhpUEtJiQu8KejmVQuEEagloyrt7aY",
	"Y11p2Zr1g6fgotb9cAcxEgiPFkvCvrfKkdoo6DRrQUcro0Wrcw2BlAkF43mDTfcmWs8VtqH0VE7kzw4Z",
	"cCZvQHyG2wo0br1QrvCckWJzblYnOS8lUZCCQM5yHchxC6bOSYo66l8HALqUQsMyAixJQOsrNKvCseKz",
	"AhdrxW5Erai2yrRgV+P0xtbGwSG7wm75DYl66smrUnS7yfMevUaiXnLc7qQ9iaiGpFIcx3+adOMsvQam",
	"QB1Xrg66p19rVT98OaOR68yNJPd1pnqGWNKJEWxLrNGaY26+fGLX5PiPAY3oHShtUw49PIgPYmOmLEGw",
	"ktM+fXUQH7yiES0ZZlabHiv5ixsY24eRiw7DCzNpa5AayVyjqzyaGkycQ9r1L+PYcicF+lTOyjLnid3c",
	"+6pd4nOp1vziCIVelZF9lZtMjWZKsbGzupFS6e8fzaqj+HAjJTqrge1jAkedC1ZhJhX/C9IGsbR/0aT0",
	"4nJyGVFdFQUz7aSFzzBDDMhkKBXBDIiRZpJIYpyHGL8yppRSBwhwM4OHxXklaPxFpuOt2T1rLiZNx0dV",
	"wWSJ9e0B3pyHAsD7BeTfv/8hjZxJuCY6k/eCSJGPiRQJOG842oM3aFBESCRDWQnvD1PCncaEEQH3NfGW",
	"d+Z5nkSzqOs9OqMG6cS1DDkgLLvAZzuiTl2gZIoVgKC0dT+T4W1E171kn9ZS6SKZ0ZztK+qm8eMF4o+W",
	"+hp6KsmJB/t5gnFPnJ826V43/B1zhInaFRz/SfbCtpUW166wP8lcm7yzuHfi9xz2jZG7PerbIusk58nN",
	"e1lpIBZF8gOCRgIiLSUX+KPDeD2A/4d3EV7hQHUgZtOJPdgcvAP0M/0TW4Muc/wJLR1Awwa3lCQZJDfO",
	"gGnP0drcDOyKcFa9rUCNZ2k15wVHOp9DUxiyKkfafxnbCYoXZlg4jGM7EvmnwKR8uY9Wys6lazRStkeR",
	"Q+KENhG131ie1x+7uxR74s6Cydmz31ianblZDHG3r/bA3iPvLvFv7HuP3+oCz5+htO+/yk5xdejUuJLr",
	"MRm8sZN6S1J6PhzjnXtePfY8Ix3vABe5MJ4+vYzoShFn/s5gFzmicWm0VqKIt322v6/p4C3ePW+/ca25",
	"GBGpCBd3LOcpGXLIU723Hn3gj527LYuIuxlKI6OX/9dt2hLPnOvtQ5IxMQI/782L8HPUhy9nxN1AEedy",
	"1vvMdLWy3bO3TzsrUOduwNtrgZqd2VKgDOM/72coNknVkGtvxwjLFbB0TJDVHLVMyX4unkz+CwAA///k",
	"Pi+Cox4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
